language: c
env:
  - WHYCONF=$PWD/.why3.conf

install:
  - ./scripts/install-dependencies.sh
  - export PATH=$PWD/z3-4.6.0-x64-ubuntu-14.04/bin:$PATH
  - export PATH=$PWD:$PATH
  - export PATH=$PWD/spark-discovery-gpl-2017-x86_64-linux-bin/bin:$PATH
  - $PWD/spark-discovery-gpl-2017-x86_64-linux-bin/libexec/spark/bin/why3config --detect-provers
  - cvc4 --version
  - cat /home/travis/.why3.conf

script:
  # - make all-travis
  # - cat $PWD/non-mutating/gnatprove/gnatprove.out
  - cd non-mutating; gnatprove -P non_mutating_algorithms.gpr -f  --output-header --prover=cvc4 --timeout=15 --why3-conf=/home/travis/.why3.conf find_p.adb
